language: python
python:
  - "2.7"
  - "3.6"

# command to install tools
before_install:
  - sudo apt-get -qq update

# command to install dependencies
install:
  - pip install .

# command to run the tests
script:
  - nosetests

# branches to build
branches:
  only:
    - master
