name: windcraft-CI

on:
   push:
     branches: [master]
   pull_request:
     branches: [master]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Formatting
        run: uv run ruff format --check
      - name: Checks
        run: uv run ruff check
      - name: Docs
        run: uv run sphinx-build -M html ./docs ./build --fail-on-warning
