name: windcraft-Docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-docs
  cancel-in-progress: true

jobs:
  Docs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Docs
        run: uv run sphinx-build -b html docs docs/_build/html
      - name: Deploy
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{runner.workspace}}/docs/_build/html
          SINGLE_COMMIT: true
